### ISSUE TITLE
Issues converting .json to .kva file

### ISSUE THREAD

**Issue by PeteCrowe** [sitony/kinovea#1]
Hello, and thank you for your work in converting OpenPose .json files to Kinovea.

I happen to be needing this capability right now. I've attempted to follow your excellent directions, but first ran into problems with numpy being missing, then cv2, then lxml. After installing all those modules, it then almost worked. It was able to numerate all the .json files, it sensed the fps in the .avi file, but then spat out the following error:

+++++++++++++++++++++++++++++++++++++++++++++++

JSON frame count:  234
Video: output.avi , Width: 1280 , Height: 720 , FPS: 59.949 , frames: 234.0
Traceback (most recent call last):
  File "C:\Users\petec\OneDrive\Documents\EagleEye\Art of Analysis videos\OpenPose work\Ohtani\JSON\js2kv.py", line 122, in <module>
    pcc, pc  = serch_neighbourhood(person_target_coord_tracked[frame-1], peoples_neck)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\petec\OneDrive\Documents\EagleEye\Art of Analysis videos\OpenPose work\Ohtani\JSON\js2kv.py", line 108, in serch_neighbourhood
    return pls[np.argmin(lst)].tolist(), np.argmin(lst)
               ^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in argmin
  File "C:\Users\petec\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 1338, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\petec\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence
+++++++++++++++++++++++++++++++++++++++++++++

I'm no python pro and can't figure out what to do next. Thanks for your help, and I hope you are still active on this.

**Comment by MoeField** [comment]
I have the same problem. It seems like there's something worng with gstreamer. (I don't now anything further)...
